Fix missing stackmap frames
powermock/powermock pull request #1043
Opened 2020-03-21 19:58 UTC by Vampire

When using the powermock-module-junit4-rule-agent there are `java.lang.VerifyError`s.
For example if you have some project with Spock 1.0 and use use the rule, it works just fine.
As soon as you upgrade to 1.2 or 1.3 which dropped Java 6 support, you get various of these verify errors.

They are all about "Expected stackmap frame at this location.".

I'm no Byte Buddy expert, but from what I have read, the combination of `ClassWriter.COMPUTE_MAXS` with `ClassReader.SKIP_FRAMES` is not the best idea.
`ClassReader.SKIP_FRAMES` will skip reading and visiting stack maps and stack map tables.
The JavaDoc of that attribute says it is for example useful if you use `ClassWriter.COMPUTE_FRAMES` as it recalculates the stackmap frames anyway, so there is no need to parse and visit them.
But like it is currently, they are neither parsed, nor visited, nor computed and thus they are missing when verifying.

As far as I understood there are two ways to handle this, either use `ClassWriter.COMPUTE_FRAMES` and `ClassReader.SKIP_FRAMES`,
as then the frames are not parsed or visited, but recalculated, or do not use both as they are then parsed, visited and in
the case of this visitor just copied.

As the visitor only removes the final modifiers for methods and classes now, I renamed it,
disabled even the MAXS computation and disabled the frame skipping.

From my test it seems to work better with this setting now and also all your tests are green
(except three tests that are red for me even without my changes).

2020-03-22 01:27 UTC, Vampire commented
Hm, I don't see why the tests fail in 2 of 3 builds on Travis.
They work fine here, even if I set the environment property `powermock.byte-code-framework=Javassist` like the failing builds on Travis do. :-/

2020-03-22 06:25 UTC, kriegaex commented
I tested this with Spock 1.3 (JUnit 4) and 2.0-M2 (JUnit 5), PowerMock with this fix works both with Mockito 2 and EasyMock tests.

Thus, I support this PR being accepted and a maintenance release being published ASAP. This was a long-standing problem which now seems to be solved and with it several related problems.

2020-03-29 22:30 UTC, thekingn0thing commented
@Vampire thank you for the PR. I added one small comment. Please, can you address it and then I will merge it and release a new version.

2020-03-30 00:40 UTC, Vampire commented
I happily would, if there were any.
Did you maybe not add a single commit but started a review and then didn't finish it?

2020-03-30 07:21 UTC, thekingn0thing requested changes

2020-03-30 07:21 UTC, thekingn0thing commented on powermock-modules/powermock-module-javaagent/src/main/java/org/powermock/modules/agent/DefinalizingClassTransformer.java
> +        final ClassWriter writer = new ClassWriter(0);
Can you use constant instead "magic" number 0?

2020-03-30 07:23 UTC, thekingn0thing commented
@Vampire Yes, you are right. I started review instead single comment. I haven't been used Github for a while. Sotty.

2020-03-30 11:48 UTC, Vampire commented on powermock-modules/powermock-module-javaagent/src/main/java/org/powermock/modules/agent/DefinalizingClassTransformer.java
> +        final ClassWriter writer = new ClassWriter(0);
Sure, I added one.
Btw., did you see my message on Gitter? :-)

2020-03-30 14:43 UTC, thekingn0thing approved these changes

2020-03-30 14:45 UTC, thekingn0thing commented on powermock-modules/powermock-module-javaagent/src/main/java/org/powermock/modules/agent/DefinalizingClassTransformer.java
> +        final ClassWriter writer = new ClassWriter(0);
Thanks! 
Nope, I didn't see. I haven't used Gitter for ages.

2020-03-30 14:46 UTC, merged

2024-01-29 11:25 UTC, EDGARDO-NRMA commented
Should I ran this in android test?